version: "3"
services:
  rabbit:
    image: rabbitmq:3-management
    container_name: dev-rabbitmq-server
    hostname: dev-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - /root/rabbitmq/data-rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
      
