version: '3'
services:
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    container_name: dev-redis
    hostname: dev-redis
    ports:
      - '6379:6379'
    environment:
      REDIS_REPLICATION_MODE: master
    volumes:
      - /root/redis/data-redis:/var/lib/redis
    networks:
      - redis-net-dev

networks:
  redis-net-dev:
