version: '3'
services:
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    container_name: dev-redis-server
    hostname: dev-redis
    ports:
      - '6379:6379'
    environment:
      REDIS_REPLICATION_MODE: master
    volumes:
      - /devops/docker-compose/redis/data-redis:/data
    networks:
      - redis-net-dev
    restart: unless-stopped

networks:
  redis-net-dev:
