---
# tasks file for basics
- name: Set server MOTD
  template: 
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 644

- name: update color prompt
  lineinfile:
    path: ~/.bashrc
    line: "force_color_prompt=yes"
    insertafter: EOF
  become_user: osboxes
  become: true

- name: remove cloud-init
  apt:
    name: cloud-init
    state: absent
    force_apt_get: yes

- name: remove cloud-init local data
  file:
    path: /etc/cloud
    state: absent

- name: remove cloud-init system data
  file:
    path: /var/lib/cloud
    state: absent

