---
- hosts: localhost
  gather_facts: yes
  vars_files:
    - keys.yml
  tasks:
    - name: get target-3 instance
      ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          tag:Name: target-3
      register: ec2_facts
    - debug: 
        var: ec2_facts.instances[0].instance_id

    - name: remove tags
      ec2_tag:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        resource: "{{ ec2_facts.instances[0].instance_id }}"
        tags:
          Name: 
        state: absent
        purge_tags: true

    - name: terminate instances
      ec2: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: absent
        instance_id:
          - "{{ ec2_facts.instances[0].instance_id }}"
      register: ec2
    - debug:
        var: ec2
    
    - name: get instance facts
      ec2_instance_facts: 
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters: 
          instance-state-name: stopped
      register: ec2_facts_stop
    - debug:
