---
- name: Create required directory
  file:
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes
    state: directory
  loop:
    - /home/{{ user }}/docker-compose/{{ service }}
  
- name: Copy docker-compose file
  template:
    src: "{{ service }}/docker-compose.yml"
    dest: /home/{{ user }}/docker-compose/{{ service }}
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Copy Dockerfile file
  template:
    src: "{{ service }}/Dockerfile"
    dest: /home/{{ user }}/docker-compose/{{ service }}
    owner: "{{ user }}"
    group: "{{ user }}"
  ignore_errors: yes

- name: Copy bootstrap.sh script
  template:
    src: "{{ service }}/bootstrap.sh"
    dest: /home/{{ user }}/docker-compose/{{ service }}
    owner: "{{ user }}"
    group: "{{ user }}"
  ignore_errors: yes
