- name: Restart active containers
  shell: /usr/local/bin/docker-compose -f "{{ item }}/docker-compose.yml" restart
  with_items:
    - /carnegie/docker-compose/{{ service }}
    - /home/{{ user }}/docker-compose/{{ service }}
  ignore_errors: yes
