#- name: Copy docker-compose.yml to remote host
#  copy: 
#    src: files/redis/docker-compose.yml
#    dest: /tmp/

- name: Create and start services
  docker_compose:
    project_src: "{{ item }}"
    state: present
  register: output
  become: yes 
  with_items:
    - ~/redis
    - ~/rabbitmq
