# This method  is not working on Amazon Centos Nodes as docker_compose cant recognize installed docker-compose because of some missing dependencies that cant be additionally installed 
#- name: Stop active containers
#  docker_compose:
#    project_src: "{{ item }}"
#    stopped: yes
#  loop:
#    - /home/{{ user }}/docker-compose/{{ service }}
#  when: ansible_facts['distribution'] == 'Ubuntu'

# This method is used for Amazon instances
- name: Stop active containers
  shell: /usr/local/bin/docker-compose -f "{{ item }}/docker-compose.yml" down
  with_items:
    - /carnegie/docker-compose/{{ service }}
    - /home/{{ user }}/docker-compose/{{ service }}
  ignore_errors: yes
