- name: Check is docker installed
  command: systemctl status docker
  register: docker_check
  ignore_errors: yes

- name: Download dependencies required for installing docker
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add docker repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: docker_check.stderr.find('service could not be found') != -1

#- name: Add docker repository
#  get_url:
#    url: https://download.docker.com/linux/centos/docker-ce.repo
#    dest: /etc/yum.repos.d/docker-ce.repo
#  when: docker_check.stderr.find('service could not be found') != -1

- name: Install docker
  package:
    name: docker-ce
    state: latest
  when: docker_check.stderr.find('service could not be found') != -1

- name: Enabled docker daemon
  systemd: 
    name: docker
    enabled: yes

- name: Start docker service
  service:
    name: docker
    state: started

- name: Add ec2-user to docker group
  user:
    name: osboxes
    groups: docker
    append: yes

- name: Check is docker-compose installed
  command: docker-compose --version
  register: docker_compose_check
  ignore_errors: yes

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 0755
  when:
    - docker_compose_check.msg is defined
    - docker_compose_check.msg.find('No such file or directory') != -1

