---
- import_tasks: install_amazon.yml
  tags: [install_amazon]

- import_tasks: install_ubuntu.yml
  tags: [install_ubuntu]
  
- import_tasks: uninstall.yml
  tags: [uninstall]

- import_tasks: prepare.yml
  tags: [prepare]

- import_tasks: docker-compose-up.yml
  tags: [compose-up]

- import_tasks: docker-compose-down.yml
  tags: [compose-down]

- import_tasks: copy.yml
  tags: [copy]
