---
# tasks file for roles/docker
- import_tasks: install.yml
  tags: [install]

- import_tasks: prepare.yml
  tags: [prepare]

- import_tasks: docker-compose-up.yml
  tags: [compose-up]

- import_tasks: copy.yml
  tags: [copy]
 
- import_tasks: docker-compose-down.yml
  tags: [compose-down]
