- name: Recommended to set the Linux kernel overcommit memory settings
  sysctl:
    name: vm.overcommit_memory
    value: '1'
    sysctl_file: /etc/sysctl.conf
    state: present
    reload: yes

# Transparent Huge Pages (causes latency and mem usage issues with redis) - need to disable
- name: Disable THP in kernel
  template: 
    src: 'redis/disable-transparent-huge-pages.service'
    dest: /etc/systemd/system/disable-transparent-huge-pages.service
    owner: root
    group: root
    mode: 0755
  register: stat_thp

- name: Start, Enable service disable-transparent-huge-pages.service
  systemd:
    daemon_reload: yes
    name: disable-transparent-huge-pages.service
    state: started
    enabled: yes
  when: stat_thp.stat.isfile is defined and stat_thp.stat.isfile
  ignore_errors: yes

- name: Prepare repository to download required packages
  yum:
    name: epel-release
    state: present
  when: ansible_facts['distribution'] == 'Amazon'
#- name: Prepare repository to download required packages
#  yum_repository:
#    name: ius-release
#    description: ius repo
#    baseurl: https://repo.ius.io/ius-release-el7.rpm

#- name: Disable THP in kernel second method- not working because from some reason its not done as user root from remote host, even if specified
#  command: "{{ item }}"
#  with_items:
#    - echo "never" > /sys/kernel/mm/transparent_hugepage/enabled
#    - echo "never" > /sys/kernel/mm/transparent_hugepage/defrag
#  become: yes
#  become_user: root
